// Generated by Wrangler — do not edit manually.
// Run: npx wrangler types to regenerate.

declare module "cloudflare:workers" {
  export const env: {
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    SUPABASE_ANON_KEY: string;
    SUPABASE_PUBLISHABLE_KEY: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    SUPABASE_URL: string;
    VITE_STRIPE_PUBLISHABLE_KEY: string;
    VITE_SUPABASE_PUBLISHABLE_KEY: string;
    VITE_SUPABASE_URL: string;
    ASSETS: Fetcher;
  };
}
