/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KassaRouteImport } from './routes/kassa'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBestallningarRouteImport } from './routes/admin.bestallningar'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProdukterRouteImport } from './routes/admin.produkter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KassaRoute = KassaRouteImport.update({
  id: '/kassa',
  path: '/kassa',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBestallningarRoute = AdminBestallningarRouteImport.update({
  id: '/bestallningar',
  path: '/bestallningar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukterRoute = AdminProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/shop': typeof ShopRoute
  '/admin/bestallningar': typeof AdminBestallningarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/shop': typeof ShopRoute
  '/admin/bestallningar': typeof AdminBestallningarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/shop': typeof ShopRoute
  '/admin/bestallningar': typeof AdminBestallningarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kassa'
    | '/kontakt'
    | '/om-oss'
    | '/shop'
    | '/admin/bestallningar'
    | '/admin/login'
    | '/admin/produkter'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kassa'
    | '/kontakt'
    | '/om-oss'
    | '/shop'
    | '/admin/bestallningar'
    | '/admin/login'
    | '/admin/produkter'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kassa'
    | '/kontakt'
    | '/om-oss'
    | '/shop'
    | '/admin/bestallningar'
    | '/admin/login'
    | '/admin/produkter'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KassaRoute: typeof KassaRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kassa': {
      id: '/kassa'
      path: '/kassa'
      fullPath: '/kassa'
      preLoaderRoute: typeof KassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bestallningar': {
      id: '/admin/bestallningar'
      path: '/bestallningar'
      fullPath: '/admin/bestallningar'
      preLoaderRoute: typeof AdminBestallningarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produkter': {
      id: '/admin/produkter'
      path: '/produkter'
      fullPath: '/admin/produkter'
      preLoaderRoute: typeof AdminProdukterRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBestallningarRoute: typeof AdminBestallningarRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProdukterRoute: typeof AdminProdukterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBestallningarRoute: AdminBestallningarRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProdukterRoute: AdminProdukterRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KassaRoute: KassaRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
