/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as KassaRouteImport } from './routes/kassa'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KopvillkorRouteImport } from './routes/kopvillkor'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBestallningarRouteImport } from './routes/admin.bestallningar'
import { Route as AdminProdukterRouteImport } from './routes/admin.produkter'
import { Route as BetalningBehandlarRouteImport } from './routes/betalning.behandlar'
import { Route as BetalningLyckadRouteImport } from './routes/betalning.lyckad'
import { Route as BetalningMisslyckadRouteImport } from './routes/betalning.misslyckad'
import { Route as ProduktIdRouteImport } from './routes/produkt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const KassaRoute = KassaRouteImport.update({
  id: '/kassa',
  path: '/kassa',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KopvillkorRoute = KopvillkorRouteImport.update({
  id: '/kopvillkor',
  path: '/kopvillkor',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBestallningarRoute = AdminBestallningarRouteImport.update({
  id: '/bestallningar',
  path: '/bestallningar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukterRoute = AdminProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => AdminRoute,
} as any)
const BetalningBehandlarRoute = BetalningBehandlarRouteImport.update({
  id: '/betalning/behandlar',
  path: '/betalning/behandlar',
  getParentRoute: () => rootRouteImport,
} as any)
const BetalningLyckadRoute = BetalningLyckadRouteImport.update({
  id: '/betalning/lyckad',
  path: '/betalning/lyckad',
  getParentRoute: () => rootRouteImport,
} as any)
const BetalningMisslyckadRoute = BetalningMisslyckadRouteImport.update({
  id: '/betalning/misslyckad',
  path: '/betalning/misslyckad',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktIdRoute = ProduktIdRouteImport.update({
  id: '/produkt/$id',
  path: '/produkt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/kopvillkor': typeof KopvillkorRoute
  '/om-oss': typeof OmOssRoute
  '/shop': typeof ShopRoute
  '/admin/bestallningar': typeof AdminBestallningarRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/betalning/behandlar': typeof BetalningBehandlarRoute
  '/betalning/lyckad': typeof BetalningLyckadRoute
  '/betalning/misslyckad': typeof BetalningMisslyckadRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/kopvillkor': typeof KopvillkorRoute
  '/om-oss': typeof OmOssRoute
  '/shop': typeof ShopRoute
  '/admin/bestallningar': typeof AdminBestallningarRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/betalning/behandlar': typeof BetalningBehandlarRoute
  '/betalning/lyckad': typeof BetalningLyckadRoute
  '/betalning/misslyckad': typeof BetalningMisslyckadRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kassa': typeof KassaRoute
  '/kontakt': typeof KontaktRoute
  '/kopvillkor': typeof KopvillkorRoute
  '/om-oss': typeof OmOssRoute
  '/shop': typeof ShopRoute
  '/admin/bestallningar': typeof AdminBestallningarRoute
  '/admin/produkter': typeof AdminProdukterRoute
  '/betalning/behandlar': typeof BetalningBehandlarRoute
  '/betalning/lyckad': typeof BetalningLyckadRoute
  '/betalning/misslyckad': typeof BetalningMisslyckadRoute
  '/produkt/$id': typeof ProduktIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/integritetspolicy'
    | '/kassa'
    | '/kontakt'
    | '/kopvillkor'
    | '/om-oss'
    | '/shop'
    | '/admin/bestallningar'
    | '/admin/produkter'
    | '/betalning/behandlar'
    | '/betalning/lyckad'
    | '/betalning/misslyckad'
    | '/produkt/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integritetspolicy'
    | '/kassa'
    | '/kontakt'
    | '/kopvillkor'
    | '/om-oss'
    | '/shop'
    | '/admin/bestallningar'
    | '/admin/produkter'
    | '/betalning/behandlar'
    | '/betalning/lyckad'
    | '/betalning/misslyckad'
    | '/produkt/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/integritetspolicy'
    | '/kassa'
    | '/kontakt'
    | '/kopvillkor'
    | '/om-oss'
    | '/shop'
    | '/admin/bestallningar'
    | '/admin/produkter'
    | '/betalning/behandlar'
    | '/betalning/lyckad'
    | '/betalning/misslyckad'
    | '/produkt/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KassaRoute: typeof KassaRoute
  KontaktRoute: typeof KontaktRoute
  KopvillkorRoute: typeof KopvillkorRoute
  OmOssRoute: typeof OmOssRoute
  ShopRoute: typeof ShopRoute
  BetalningBehandlarRoute: typeof BetalningBehandlarRoute
  BetalningLyckadRoute: typeof BetalningLyckadRoute
  BetalningMisslyckadRoute: typeof BetalningMisslyckadRoute
  ProduktIdRoute: typeof ProduktIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kassa': {
      id: '/kassa'
      path: '/kassa'
      fullPath: '/kassa'
      preLoaderRoute: typeof KassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopvillkor': {
      id: '/kopvillkor'
      path: '/kopvillkor'
      fullPath: '/kopvillkor'
      preLoaderRoute: typeof KopvillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bestallningar': {
      id: '/admin/bestallningar'
      path: '/bestallningar'
      fullPath: '/admin/bestallningar'
      preLoaderRoute: typeof AdminBestallningarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produkter': {
      id: '/admin/produkter'
      path: '/produkter'
      fullPath: '/admin/produkter'
      preLoaderRoute: typeof AdminProdukterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/betalning/behandlar': {
      id: '/betalning/behandlar'
      path: '/betalning/behandlar'
      fullPath: '/betalning/behandlar'
      preLoaderRoute: typeof BetalningBehandlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betalning/lyckad': {
      id: '/betalning/lyckad'
      path: '/betalning/lyckad'
      fullPath: '/betalning/lyckad'
      preLoaderRoute: typeof BetalningLyckadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betalning/misslyckad': {
      id: '/betalning/misslyckad'
      path: '/betalning/misslyckad'
      fullPath: '/betalning/misslyckad'
      preLoaderRoute: typeof BetalningMisslyckadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$id': {
      id: '/produkt/$id'
      path: '/produkt/$id'
      fullPath: '/produkt/$id'
      preLoaderRoute: typeof ProduktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBestallningarRoute: typeof AdminBestallningarRoute
  AdminProdukterRoute: typeof AdminProdukterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBestallningarRoute: AdminBestallningarRoute,
  AdminProdukterRoute: AdminProdukterRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KassaRoute: KassaRoute,
  KontaktRoute: KontaktRoute,
  KopvillkorRoute: KopvillkorRoute,
  OmOssRoute: OmOssRoute,
  ShopRoute: ShopRoute,
  BetalningBehandlarRoute: BetalningBehandlarRoute,
  BetalningLyckadRoute: BetalningLyckadRoute,
  BetalningMisslyckadRoute: BetalningMisslyckadRoute,
  ProduktIdRoute: ProduktIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
